apiVersion: v1
kind: Namespace
metadata:
  name: rpsls-duel
  labels:
    app.kubernetes.io/part-of: playhub-demo-game
    playhub.io/game-id: rock-paper-scissors-lizard-robot
    playhub.io/production-host: rpsls-duel.win
